# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: budget-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    darwin: macOS
  files:
    - budgetTypeMapping.json

env_files:
  github_token: ~/.github/budget-cli-release-token